from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import (
    AdminDashboardView,
    BookingCreateView,
    BookingDetailView,
    BookingListView,
    BookingReceiptView,
    CustomerDetailView,
    HomeRedirectView,
    InventoryListView,
    InventoryAlertsView,
    NotificationsView,
    PaymentCreateView,
    PaymentListView,
    PaymentReceiptView,
    RoleDashboardRedirectView,
    ReturnTrackerView,
    RentalItemCreateView,
    RentalItemListView,
    RentalItemUpdateView,
    ReportsView,
    SettingsView,
    StaffAccountUpdateView,
    StaffDashboardView,
    StaffLoginView,
    booking_availability,
    booking_action,
    notification_action,
    notification_bulk_action,
    notification_open,
    report_export,
    staff_account_action,
)

urlpatterns = [
    path("", HomeRedirectView.as_view(), name="home"),
    path("login/", StaffLoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("dashboard/", RoleDashboardRedirectView.as_view(), name="dashboard"),
    path("dashboard/admin/", AdminDashboardView.as_view(), name="admin-dashboard"),
    path("dashboard/staff/", StaffDashboardView.as_view(), name="staff-dashboard"),
    path("items/", RentalItemListView.as_view(), name="item-list"),
    path("items/add/", RentalItemCreateView.as_view(), name="item-add"),
    path("items/<int:pk>/edit/", RentalItemUpdateView.as_view(), name="item-edit"),
    path("customers/<int:pk>/", CustomerDetailView.as_view(), name="customer-detail"),
    path("bookings/", BookingListView.as_view(), name="booking-list"),
    path("bookings/add/", BookingCreateView.as_view(), name="booking-add"),
    path("bookings/availability/", booking_availability, name="booking-availability"),
    path("bookings/<int:pk>/", BookingDetailView.as_view(), name="booking-detail"),
    path("bookings/<int:pk>/receipt/", BookingReceiptView.as_view(), name="booking-receipt"),
    path("bookings/<int:pk>/action/<str:action>/", booking_action, name="booking-action"),
    path("inventory/", InventoryListView.as_view(), name="inventory"),
    path("inventory/alerts/", InventoryAlertsView.as_view(), name="inventory-alerts"),
    path("returns/", ReturnTrackerView.as_view(), name="return-tracker"),
    path("notifications/", NotificationsView.as_view(), name="notifications"),
    path("notifications/<int:pk>/open/", notification_open, name="notification-open"),
    path("notifications/<int:pk>/action/<str:action>/", notification_action, name="notification-action"),
    path("notifications/action/<str:action>/", notification_bulk_action, name="notification-bulk-action"),
    path("payments/", PaymentListView.as_view(), name="payment-list"),
    path("bookings/<int:booking_pk>/payments/add/", PaymentCreateView.as_view(), name="payment-add"),
    path("payments/<int:pk>/receipt/", PaymentReceiptView.as_view(), name="payment-receipt"),
    path("reports/", ReportsView.as_view(), name="reports"),
    path("reports/export/<str:report_type>/", report_export, name="report-export"),
    path("settings/", SettingsView.as_view(), name="settings"),
    path("settings/staff/<int:pk>/edit/", StaffAccountUpdateView.as_view(), name="staff-edit"),
    path("settings/staff/<int:pk>/action/<str:action>/", staff_account_action, name="staff-action"),
]
